### GET ALL JSON ROOMS
GET http://localhost:8000/api/rooms

### GET JSON ROOM BY ID

GET http://localhost:8000/api/rooms/C307

### CREATE JSON ROOM

POST http://localhost:8000/api/rooms
Content-Type: application/json

{
  "code_room": "C307",
  "name": "Ruang Kelas",
  "notes": "Lantai 3",
  "capacity": 50
}

### UPDATE JSON ROOM BY ID
PUT http://localhost:8000/api/rooms/C307
Content-Type: application/json

{
  "code_room": "C307",
  "name": "Ruang Lab Komputer",
  "notes": "Lantai 3",
  "capacity": 20
}

### DELETE JSON ROOM BY ID
DELETE http://localhost:8000/api/rooms/C307


### GET ALL JSON TOOLS
GET http://localhost:8000/api/tools

### GET JSON TOOL BY ID
GET http://localhost:8000/api/tools/1

### CREATE JSON TOOL
POST http://localhost:8000/api/tools
Content-Type: application/json

{
  "name": "Kursi",
  "notes": "Dilarang bersender",
  "quantity": 100
}

### UPDATE JSON TOOL BY ID
PUT http://localhost:8000/api/tools/1
Content-Type: application/json

{
  "name": "Monitor",
  "notes": "Merk Infinix",
  "quantity": 10,
  "status" : "available"
}

### DELETE JSON TOOL BY ID
DELETE http://localhost:8000/api/tools/2